app/views/shared/_footer.html.erb

edited footer as it was throwing error

edited footer

---

app/assets/stylesheets/components/_footer.scss

improved footer

---

app/controllers/experiences_controller.rb
app/views/experiences/_index_card.html.erb
app/views/experiences/index.html.erb

in the views/experiences/index.html:
- create simple search-bar for title and description
- display cards in index page

create search bar experience and display index page experience

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search.scss
app/views/experiences/index.html.erb

updated style for search-bar in index page

update style for search-bar

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

links for navbar

---

.gitignore
app/views/bookings/new.html.erb
app/views/experiences/_index_card.html.erb

1. created link image to show-page
2. created link title to show-page
3. created link `book now` button to new form booking

Index page links

---

app/assets/stylesheets/components/_show_card.scss
app/models/booking.rb
app/views/experiences/_show_card.html.erb
app/views/ratings/_new_rating.html.erb

book now button links to /experiences/:id/bookings/new
review button links to bookings/:id/ratings/new

Show links

---

app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/pages/home.html.erb

updated style button of forms (eg. sign-up form; log-in form)

update button style of forms

---

app/assets/stylesheets/components/_search.scss
app/assets/stylesheets/components/_show_card.scss
app/controllers/experiences_controller.rb
app/controllers/ratings_controller.rb
app/views/experiences/_index_card.html.erb
app/views/experiences/_rating_card.html.erb
app/views/experiences/_rating_list.html.erb
app/views/experiences/_show_card.html.erb
config/routes.rb

Ratings box in show page with all ratings displayed for each experience

Ratings show

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_show_card.scss
app/assets/stylesheets/components/_special_card.scss
app/views/experiences/_show_card.html.erb
app/views/special_days/index.html.erb

edited styling of card on specialdays

edited styling of card on specialdays

---

app/assets/stylesheets/components/_about.scss
app/assets/stylesheets/components/_contact_us.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/about.html.erb
app/views/pages/contact.html.erb
app/views/pages/home.html.erb

about us and contact us page

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

responsive images on home page

responsive images on home page

---

app/assets/stylesheets/components/_show_card.scss

increased reviews container

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/javascript/controllers/index.js
app/javascript/controllers/popover_controller.js
app/views/experiences/_favorites.html.erb
app/views/experiences/_index_card.html.erb
package-lock.json
package.json
yarn.lock

add popover for favorite icon on experience_card

---

app/assets/stylesheets/components/_show_card.scss
app/views/experiences/_img_carousel.html.erb
app/views/experiences/_show_card.html.erb

3 images displayed in the show page carousel and styling added

images and styling

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_special_card.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_index_page.scss
app/assets/stylesheets/pages/_mood_index.scss
app/views/experiences/index.html.erb
app/views/experiences/mood.html.erb
app/views/special_days/index.html.erb

improved styling

---

app/assets/stylesheets/components/_carousel.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_mood_carousel.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_second_banner.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index_page.scss
app/views/experiences/_mood_carousel.html.erb
app/views/experiences/index.html.erb
app/views/pages/_carousel.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

added second banner and improved styling

Second banner

---

app/assets/stylesheets/components/_index_card.scss
app/views/experiences/_index_card.html.erb

improve index card

---

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

fixed navbar dropdown

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index_card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_second_banner.scss
app/assets/stylesheets/pages/_home.scss
app/views/experiences/_index_card.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

increased size of elements on home page and index cards

increased size of elements on home page and index cards

---

app/assets/stylesheets/components/_book_card.scss
app/views/bookings/_book.html.erb
app/views/bookings/_secret_book.html.erb
app/views/bookings/index.html.erb

Make it more nicer a little bit ✌️ 
BEFORE
AFTER

Improve booking index page

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

removed transition

---

app/assets/stylesheets/components/_about.scss
app/assets/stylesheets/components/_book_card.scss
app/assets/stylesheets/components/_second_banner.scss
app/views/bookings/_book.html.erb
app/views/bookings/_secret_book.html.erb
app/views/bookings/index.html.erb
app/views/experiences/my_favorite.html.erb
app/views/pages/about.html.erb

Contact pg

---

app/assets/stylesheets/components/_book_card.scss
app/assets/stylesheets/components/_second_banner.scss
app/views/bookings/_book.html.erb
app/views/bookings/index.html.erb
app/views/experiences/my_favorite.html.erb

styling booking page completed

---

app/assets/stylesheets/components/_book_card.scss
app/assets/stylesheets/components/_second_banner.scss
app/views/bookings/_book.html.erb
app/views/bookings/_secret_book.html.erb
app/views/bookings/index.html.erb
app/views/experiences/my_favorite.html.erb

Book will see

---

app/controllers/experiences_controller.rb
db/sed.rb
db/seeds.rb

3 new dates

---

app/assets/stylesheets/components/_about.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

dropdown made visible over video

dropdown made visible

---

app/assets/stylesheets/components/_footer.scss
db/seeds.rb

added seeds

---

app/views/experiences/_rating.html.erb

popups added to reviews

---

app/views/experiences/index.html.erb
db/seeds.rb

fixed mood carousel on index page

fixed mood carousel on index page
